version: "3"

services:
  server:
    build: .
    ports:
      - 5001:5000
    volumes:
      - ../twauth-web/:/usr/src/app/
    command: pipenv run python3 ./twauth-web.py
    tty: true
    restart: always
