require('dotenv').config()

let TWITTER_CONSUMER_KEY = process.env.TWITTER_CONSUMER_KEY
let TWITTER_CONSUMER_SECRET = process.env.TWITTER_CONSUMER_SECRET

let TWITTER_ACCESS_TOKEN = process.env.TWITTER_ACCESS_TOKEN
let TWITTER_ACCESS_TOKEN_SECRET = process.env.TWITTER_ACCESS_TOKEN_SECRET

let CULTURE_ACCESS_TOKEN = process.env.CULTURE_ACCESS_TOKEN
let CULTURE_ACCESS_TOKEN_SECRET = process.env.CULTURE_ACCESS_TOKEN_SECRET

let NB_ACCESS_TOKEN = process.env.NB_ACCESS_TOKEN
let NB_ACCESS_TOKEN_SECRET = process.env.NB_ACCESS_TOKEN_SECRET

let FSA_ACCESS_TOKEN = process.env.FSA_ACCESS_TOKEN
let FSA_ACCESS_TOKEN_SECRET = process.env.FSA_ACCESS_TOKEN_SECRET

let CNS_ACCESS_TOKEN = process.env.CNS_ACCESS_TOKEN
let CNS_ACCESS_TOKEN_SECRET = process.env.CNS_ACCESS_TOKEN_SECRET

let LATINO_ACCESS_TOKEN = process.env.LATINO_ACCESS_TOKEN
let LATINO_ACCESS_TOKEN_SECRET = process.env.LATINO_ACCESS_TOKEN_SECRET
module.exports ={
    TWITTER_CONSUMER_KEY,
    TWITTER_CONSUMER_SECRET,
    TWITTER_ACCESS_TOKEN,
    TWITTER_ACCESS_TOKEN_SECRET,
    CULTURE_ACCESS_TOKEN,
    CULTURE_ACCESS_TOKEN_SECRET,
    NB_ACCESS_TOKEN,
    NB_ACCESS_TOKEN_SECRET,
    FSA_ACCESS_TOKEN,
    FSA_ACCESS_TOKEN_SECRET,
    CNS_ACCESS_TOKEN,
    CNS_ACCESS_TOKEN_SECRET,
    LATINO_ACCESS_TOKEN,
    LATINO_ACCESS_TOKEN_SECRET,
}