require('dotenv').config()

let TWITTER_ACCESS_TOKEN = process.env.TWITTER_ACCESS_TOKEN
let TWITTER_ACCESS_TOKEN_SECRET = process.env.TWITTER_ACCESS_TOKEN_SECRET
let TWITTER_CONSUMER_KEY = process.env.TWITTER_CONSUMER_KEY
let TWITTER_CONSUMER_SECRET = process.env.TWITTER_CONSUMER_SECRET
module.exports ={
    TWITTER_ACCESS_TOKEN,
    TWITTER_ACCESS_TOKEN_SECRET,
    TWITTER_CONSUMER_KEY,
    TWITTER_CONSUMER_SECRET
}